#!/usr/bin/env bash
BE='bundle exec'
RU='rvm'

RVM_ENVIR=/home/yebyen/.rvm/scripts/rvm
RUBY_VERS=2.0.0

   API="https://www.beeminder.com/api/v1"
  JSON="goals/20-minutes/datapoints.json"
  TOKEN="auth_token=SECRETCODESATBEEHIVE"
curl -s "$API/users/yebyenw/$JSON?$TOKEN" > 20-minutes.json

 .  $RVM_ENVIR
$RU $RUBY_VERS
  ./20graph.rb

:<<EO
sqlite> .schema
CREATE TABLE minutes ( timestamp INT, 
    value DOUBLE,
    comment STRING, 
    id STRING,
    updated_at INT,
    requestid);
EO
